spring:
  datasource:
    password: 222222
    url: jdbc:mysql://127.0.0.1:3306/my_tool?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
     &serverTimezone=Asia/Shanghai
    username: root
  redis:
    database: 0
    jedis:
      pool:
        max-wait: 30000ms
        max-idle: 5
        max-active: 20
        min-idle: 5
        timeout: 2000-5000   #建立连接的超时时间2-5秒
        soTimeout: 2000-5000 #执行指令的超时时间（如果有这项配置）
        testOnBorrow: true   #在从连接池取连接时检查有效性
        testWhileIdle: true  #在空闲时检测连接有效性
    password:
    host: 127.0.0.1
    port: 6379
    timeout: 1000ms
mybatis:
  mapper-locations: classpath*:mapper/*.xml
tiny-url:
  address: http://127.0.0.1:8081
  seq:
    increment-step: 5
logging:
  level:
    com:
      zaxxer:
        hikari: debug
    xyz.hellothomas: debug
    root: info
debug: true